// <auto-generated />
using HotelariaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace hotelariaApi.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260214004459_AtualizaPermissoesMenu")]
    partial class AtualizaPermissoesMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelariaApi.Domain.Funcionalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PerfilId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Funcionalidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Visualizar indicadores e métricas",
                            Nome = "DASHBOARD"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Visualizar status e gerenciar quartos",
                            Nome = "MAPA_QUARTOS"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Gerenciar lista e detalhes de reservas",
                            Nome = "RESERVAS"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Lançar e gerenciar itens de consumo",
                            Nome = "CONSUMO"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Acesso a contas e faturamento",
                            Nome = "FINANCEIRO"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Acesso a configurações do sistema e perfis",
                            Nome = "CONFIGURACOES"
                        });
                });

            modelBuilder.Entity("HotelariaApi.Domain.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Admin"
                        });
                });

            modelBuilder.Entity("HotelariaApi.Domain.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("HotelariaApi.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hotel.com",
                            PerfilId = 1,
                            SenhaHash = "123456"
                        });
                });

            modelBuilder.Entity("HotelariaApi.Domain.Funcionalidade", b =>
                {
                    b.HasOne("HotelariaApi.Domain.Perfil", null)
                        .WithMany("Funcionalidades")
                        .HasForeignKey("PerfilId");
                });

            modelBuilder.Entity("HotelariaApi.Domain.Usuario", b =>
                {
                    b.HasOne("HotelariaApi.Domain.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("HotelariaApi.Domain.Perfil", b =>
                {
                    b.Navigation("Funcionalidades");
                });
#pragma warning restore 612, 618
        }
    }
}
