// <auto-generated />
using HotelariaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace hotelariaApi.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuncionalidadePerfil", b =>
                {
                    b.Property<int>("FuncionalidadesId")
                        .HasColumnType("integer");

                    b.Property<int>("PerfisId")
                        .HasColumnType("integer");

                    b.HasKey("FuncionalidadesId", "PerfisId");

                    b.HasIndex("PerfisId");

                    b.ToTable("FuncionalidadePerfil");

                    b.HasData(
                        new
                        {
                            FuncionalidadesId = 1,
                            PerfisId = 1
                        },
                        new
                        {
                            FuncionalidadesId = 2,
                            PerfisId = 1
                        },
                        new
                        {
                            FuncionalidadesId = 3,
                            PerfisId = 1
                        },
                        new
                        {
                            FuncionalidadesId = 4,
                            PerfisId = 1
                        },
                        new
                        {
                            FuncionalidadesId = 5,
                            PerfisId = 1
                        },
                        new
                        {
                            FuncionalidadesId = 6,
                            PerfisId = 1
                        });
                });

            modelBuilder.Entity("HotelariaApi.Domain.Funcionalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Funcionalidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Visualizar indicadores e métricas",
                            Nome = "Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Visualizar status e gerenciar quartos",
                            Nome = "MapaQuartos"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Gerenciar lista e detalhes de reservas",
                            Nome = "Reservas"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Lançar e gerenciar itens de consumo",
                            Nome = "Consumo"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Acesso a contas e faturamento",
                            Nome = "Financeiro"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Acesso a configurações do sistema e perfis",
                            Nome = "Configuracoes"
                        });
                });

            modelBuilder.Entity("HotelariaApi.Domain.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Perfis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Admin"
                        });
                });

            modelBuilder.Entity("HotelariaApi.Domain.Pousada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckInPadrao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckOutPadrao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pousada");
                });

            modelBuilder.Entity("HotelariaApi.Domain.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("HotelariaApi.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "senha");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FuncionalidadePerfil", b =>
                {
                    b.HasOne("HotelariaApi.Domain.Funcionalidade", null)
                        .WithMany()
                        .HasForeignKey("FuncionalidadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelariaApi.Domain.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelariaApi.Domain.Usuario", b =>
                {
                    b.HasOne("HotelariaApi.Domain.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
