-- A base atual pode ser descartada conforme alinhado.
-- Execute este script conectado ao banco da aplicacao.
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE TABLE "Funcionalidades" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        "Descricao" text NOT NULL,
        CONSTRAINT "PK_Funcionalidades" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE TABLE "Perfis" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        CONSTRAINT "PK_Perfis" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE TABLE "Pousada" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NomeFantasia" text NOT NULL,
        "RazaoSocial" text NOT NULL,
        "Cnpj" text NOT NULL,
        "Telefone" text NOT NULL,
        "Endereco" text NOT NULL,
        "Cidade" text NOT NULL,
        "CheckInPadrao" text NOT NULL,
        "CheckOutPadrao" text NOT NULL,
        CONSTRAINT "PK_Pousada" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE TABLE "Quartos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Numero" text NOT NULL,
        "Tipo" text NOT NULL,
        "Status" text NOT NULL,
        "Capacidade" integer NOT NULL,
        "PrecoBase" numeric NOT NULL,
        CONSTRAINT "PK_Quartos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE TABLE "FuncionalidadePerfil" (
        "FuncionalidadesId" integer NOT NULL,
        "PerfisId" integer NOT NULL,
        CONSTRAINT "PK_FuncionalidadePerfil" PRIMARY KEY ("FuncionalidadesId", "PerfisId"),
        CONSTRAINT "FK_FuncionalidadePerfil_Funcionalidades_FuncionalidadesId" FOREIGN KEY ("FuncionalidadesId") REFERENCES "Funcionalidades" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_FuncionalidadePerfil_Perfis_PerfisId" FOREIGN KEY ("PerfisId") REFERENCES "Perfis" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        "Email" text NOT NULL,
        "SenhaHash" text NOT NULL,
        "PerfilId" integer NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Usuarios_Perfis_PerfilId" FOREIGN KEY ("PerfilId") REFERENCES "Perfis" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    INSERT INTO "Funcionalidades" ("Id", "Descricao", "Nome")
    VALUES (1, 'Visualizar indicadores e métricas', 'Dashboard');
    INSERT INTO "Funcionalidades" ("Id", "Descricao", "Nome")
    VALUES (2, 'Visualizar status e gerenciar quartos', 'MapaQuartos');
    INSERT INTO "Funcionalidades" ("Id", "Descricao", "Nome")
    VALUES (3, 'Gerenciar lista e detalhes de reservas', 'Reservas');
    INSERT INTO "Funcionalidades" ("Id", "Descricao", "Nome")
    VALUES (4, 'Lançar e gerenciar itens de consumo', 'Consumo');
    INSERT INTO "Funcionalidades" ("Id", "Descricao", "Nome")
    VALUES (5, 'Acesso a contas e faturamento', 'Financeiro');
    INSERT INTO "Funcionalidades" ("Id", "Descricao", "Nome")
    VALUES (6, 'Acesso a configurações do sistema e perfis', 'Configuracoes');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    INSERT INTO "Perfis" ("Id", "Nome")
    VALUES (1, 'Admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    INSERT INTO "FuncionalidadePerfil" ("FuncionalidadesId", "PerfisId")
    VALUES (1, 1);
    INSERT INTO "FuncionalidadePerfil" ("FuncionalidadesId", "PerfisId")
    VALUES (2, 1);
    INSERT INTO "FuncionalidadePerfil" ("FuncionalidadesId", "PerfisId")
    VALUES (3, 1);
    INSERT INTO "FuncionalidadePerfil" ("FuncionalidadesId", "PerfisId")
    VALUES (4, 1);
    INSERT INTO "FuncionalidadePerfil" ("FuncionalidadesId", "PerfisId")
    VALUES (5, 1);
    INSERT INTO "FuncionalidadePerfil" ("FuncionalidadesId", "PerfisId")
    VALUES (6, 1);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE INDEX "IX_FuncionalidadePerfil_PerfisId" ON "FuncionalidadePerfil" ("PerfisId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    CREATE INDEX "IX_Usuarios_PerfilId" ON "Usuarios" ("PerfilId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Funcionalidades"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Funcionalidades") + 1,
            nextval(pg_get_serial_sequence('"Funcionalidades"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Perfis"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Perfis") + 1,
            nextval(pg_get_serial_sequence('"Perfis"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220021333_V1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220021333_V1', '9.0.19');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220230904_V2') THEN
    CREATE TABLE "Consumos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuartoId" integer NOT NULL,
        "Descricao" text NOT NULL,
        "Valor" numeric NOT NULL,
        "Quantidade" integer NOT NULL,
        "DataLancamento" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Consumos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220230904_V2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220230904_V2', '9.0.19');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Usuarios" DROP CONSTRAINT "FK_Usuarios_Perfis_PerfilId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Pousada" DROP CONSTRAINT "PK_Pousada";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Pousada" RENAME TO "Pousadas";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Usuarios" RENAME COLUMN "PerfilId" TO "ContaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER INDEX "IX_Usuarios_PerfilId" RENAME TO "IX_Usuarios_ContaId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Usuarios" ADD "EhDono" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Quartos" ADD "PousadaId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Pousadas" ADD "ContaId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Pousadas" ADD CONSTRAINT "PK_Pousadas" PRIMARY KEY ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    CREATE TABLE "Contas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        CONSTRAINT "PK_Contas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    CREATE TABLE "UsuariosPousadas" (
        "UsuarioId" integer NOT NULL,
        "PousadaId" integer NOT NULL,
        "PerfilId" integer NOT NULL,
        CONSTRAINT "PK_UsuariosPousadas" PRIMARY KEY ("UsuarioId", "PousadaId"),
        CONSTRAINT "FK_UsuariosPousadas_Perfis_PerfilId" FOREIGN KEY ("PerfilId") REFERENCES "Perfis" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UsuariosPousadas_Pousadas_PousadaId" FOREIGN KEY ("PousadaId") REFERENCES "Pousadas" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_UsuariosPousadas_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    CREATE INDEX "IX_Quartos_PousadaId" ON "Quartos" ("PousadaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    CREATE INDEX "IX_Pousadas_ContaId" ON "Pousadas" ("ContaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    CREATE INDEX "IX_UsuariosPousadas_PerfilId" ON "UsuariosPousadas" ("PerfilId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    CREATE INDEX "IX_UsuariosPousadas_PousadaId" ON "UsuariosPousadas" ("PousadaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Pousadas" ADD CONSTRAINT "FK_Pousadas_Contas_ContaId" FOREIGN KEY ("ContaId") REFERENCES "Contas" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Quartos" ADD CONSTRAINT "FK_Quartos_Pousadas_PousadaId" FOREIGN KEY ("PousadaId") REFERENCES "Pousadas" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    ALTER TABLE "Usuarios" ADD CONSTRAINT "FK_Usuarios_Contas_ContaId" FOREIGN KEY ("ContaId") REFERENCES "Contas" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260828025741_MultiPousada') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260828025741_MultiPousada', '9.0.19');
    END IF;
END $EF$;
COMMIT;

